# Generated by Django 3.1.7 on 2021-03-30 14:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myTodoApp', '0004_auto_20210330_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_creation_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 30, 14, 16, 30, 185321, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_due_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 6, 14, 16, 30, 185321, tzinfo=utc)),
        ),
    ]
