# Generated by Django 3.1.7 on 2021-03-31 08:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myTodoApp', '0006_auto_20210331_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_creation_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_due_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 7, 8, 38, 53, 994392, tzinfo=utc)),
        ),
    ]
