# Generated by Django 3.1.7 on 2021-04-01 08:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myTodoApp', '0008_auto_20210401_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myTodoApp.user'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_due_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 8, 8, 25, 41, 552478, tzinfo=utc)),
        ),
    ]
