# Generated by Django 3.1.7 on 2021-04-01 08:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myTodoApp', '0010_auto_20210401_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_due_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 8, 8, 42, 53, 987885, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_text',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
