# Generated by Django 3.1.7 on 2021-04-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myTodoApp', '0016_auto_20210402_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
