# Generated by Django 3.1.7 on 2021-04-03 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myTodoApp', '0017_auto_20210403_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_creation_date',
            new_name='creation_date',
        ),
    ]
