# Generated by Django 3.1.7 on 2021-04-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myTodoApp', '0018_auto_20210403_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='list_type',
            field=models.CharField(choices=[('PS', 'Personal'), ('PF', 'Professional'), ('SC', 'Scratch')], default='PS', max_length=2),
        ),
    ]
