# Generated by Django 3.1.7 on 2021-04-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myTodoApp', '0019_todolist_list_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_complete',
            field=models.CharField(choices=[('CP', 'Complete'), ('OG', 'Ongoing')], default='OG', max_length=2),
        ),
    ]
