# Generated by Django 3.1.7 on 2021-04-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myTodoApp', '0020_auto_20210408_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_complete',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
